id: XFE Test
version: -1
name: XFE Test
description: Test XFE commands via playbook.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 41a4034d-13a0-46a6-8caf-26c0e8c4f211
    type: start
    task:
      id: 41a4034d-13a0-46a6-8caf-26c0e8c4f211
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    view: |-
      {
        "position": {
          "x": 480,
          "y": 50
        }
      }
  "1":
    id: "1"
    taskid: 88b454d8-bdf6-4124-8147-cbfb50cad63c
    type: regular
    task:
      id: 88b454d8-bdf6-4124-8147-cbfb50cad63c
      version: -1
      name: url
      description: Check the given URL reputation
      script: XFE|||url
      type: regular
      iscommand: true
      brand: XFE
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      long: {}
      threshold: {}
      url:
        simple: biicqwfvqiec.click/images/info.php
    view: |-
      {
        "position": {
          "x": 480,
          "y": 370
        }
      }
  "2":
    id: "2"
    taskid: 7d0228c7-cc3c-40d3-8a41-9b901488392d
    type: regular
    task:
      id: 7d0228c7-cc3c-40d3-8a41-9b901488392d
      version: -1
      name: VerifyContext
      description: |-
        Verifies path in context:
        - Verifies path existence
        - If matching object is an array: verify fields exists in each of the objects in the array
        - If matching object is not an array: verify fields exists in matching object
        - if 'expectedValue' is given: ensure that the given value is equal to the context path
      scriptName: VerifyContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "17"
    scriptarguments:
      expectedValue:
        simple: "3"
      fields: {}
      path:
        simple: DBotScore.Score
    view: |-
      {
        "position": {
          "x": 480,
          "y": 545
        }
      }
  "3":
    id: "3"
    taskid: 8aa9dc87-43f2-4904-88a5-74587757e8fc
    type: regular
    task:
      id: 8aa9dc87-43f2-4904-88a5-74587757e8fc
      version: -1
      name: DeleteContext
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    scriptarguments:
      all:
        simple: "yes"
      key: {}
    view: |-
      {
        "position": {
          "x": 480,
          "y": 195
        }
      }
  "4":
    id: "4"
    taskid: 5cf9c15f-35ee-48e7-856b-3d89dddeda8b
    type: regular
    task:
      id: 5cf9c15f-35ee-48e7-856b-3d89dddeda8b
      version: -1
      name: DeleteContext
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      all:
        simple: "yes"
      key: {}
    view: |-
      {
        "position": {
          "x": 480,
          "y": 895
        }
      }
  "5":
    id: "5"
    taskid: 6e7b955f-845d-47c0-8545-ad24da8af498
    type: regular
    task:
      id: 6e7b955f-845d-47c0-8545-ad24da8af498
      version: -1
      name: ip
      description: Check the given URL reputation
      script: XFE|||ip
      type: regular
      iscommand: true
      brand: XFE
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      ip:
        simple: 158.85.81.123
      long: {}
      threshold:
        simple: "4"
      url:
        simple: https://www.demisto.com
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1070
        }
      }
  "6":
    id: "6"
    taskid: 0a8db6e7-7c10-4fcd-881f-29195f5fe09e
    type: regular
    task:
      id: 0a8db6e7-7c10-4fcd-881f-29195f5fe09e
      version: -1
      name: VerifyContext
      description: |-
        Verifies path in context:
        - Verifies path existence
        - If matching object is an array: verify fields exists in each of the objects in the array
        - If matching object is not an array: verify fields exists in matching object
        - if 'expectedValue' is given: ensure that the given value is equal to the context path
      scriptName: VerifyContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "18"
    scriptarguments:
      expectedValue:
        simple: XFE
      fields: {}
      path:
        simple: IP.Malicious.Vendor
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1245
        }
      }
  "7":
    id: "7"
    taskid: 34ea6a2f-5744-426d-8028-bb03e55e20b9
    type: regular
    task:
      id: 34ea6a2f-5744-426d-8028-bb03e55e20b9
      version: -1
      name: domain
      description: Check domain reputation
      script: XFE|||domain
      type: regular
      iscommand: true
      brand: XFE
    nexttasks:
      '#none#':
      - "8"
      - "10"
    scriptarguments:
      domain:
        simple: https://www.demisto.com
      long: {}
      threshold: {}
    view: |-
      {
        "position": {
          "x": 480,
          "y": 2120
        }
      }
  "8":
    id: "8"
    taskid: 57c8e245-fbdf-4f7d-8965-ae1c2f2a5ac8
    type: regular
    task:
      id: 57c8e245-fbdf-4f7d-8965-ae1c2f2a5ac8
      version: -1
      name: VerifyContext
      description: |-
        Verifies path in context:
        - Verifies path existence
        - If matching object is an array: verify fields exists in each of the objects in the array
        - If matching object is not an array: verify fields exists in matching object
        - if 'expectedValue' is given: ensure that the given value is equal to the context path
      scriptName: VerifyContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "12"
    scriptarguments:
      expectedValue:
        simple: "1"
      fields: {}
      path:
        simple: DBotScore.Score
    view: |-
      {
        "position": {
          "x": 265,
          "y": 2295
        }
      }
  "9":
    id: "9"
    taskid: 29c641f2-47f7-48d4-830e-74d302e06ac1
    type: regular
    task:
      id: 29c641f2-47f7-48d4-830e-74d302e06ac1
      version: -1
      name: DeleteContext
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      all:
        simple: "yes"
      key: {}
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1945
        }
      }
  "10":
    id: "10"
    taskid: 0ac72df1-e5ae-4320-8cbf-6cefddee413d
    type: condition
    task:
      id: 0ac72df1-e5ae-4320-8cbf-6cefddee413d
      version: -1
      name: Check No Malicious found
      scriptName: Exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "no":
      - "12"
    scriptarguments:
      value:
        simple: ${URL.Malicious}
    view: |-
      {
        "position": {
          "x": 695,
          "y": 2295
        }
      }
  "12":
    id: "12"
    taskid: d8aeb186-b189-4c29-854f-008b3aad2cc7
    type: regular
    task:
      id: d8aeb186-b189-4c29-854f-008b3aad2cc7
      version: -1
      name: DeleteContext
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "13"
    scriptarguments:
      all:
        simple: "yes"
      key: {}
    view: |-
      {
        "position": {
          "x": 480,
          "y": 2470
        }
      }
  "13":
    id: "13"
    taskid: d1bec577-9b5e-44d2-849e-429e708f12fe
    type: regular
    task:
      id: d1bec577-9b5e-44d2-849e-429e708f12fe
      version: -1
      name: cve-latest
      description: Return the latest vulnerabilities found
      script: XFE|||cve-latest
      type: regular
      iscommand: true
      brand: XFE
    nexttasks:
      '#none#':
      - "16"
    scriptarguments:
      limit:
        simple: "1"
    view: |-
      {
        "position": {
          "x": 480,
          "y": 2645
        }
      }
  "14":
    id: "14"
    taskid: 4a3dc127-2b8d-4b1d-88e1-646b2aaf8ecf
    type: regular
    task:
      id: 4a3dc127-2b8d-4b1d-88e1-646b2aaf8ecf
      version: -1
      name: cve-search
      description: Search for details about the given CVE
      script: XFE|||cve-search
      type: regular
      iscommand: true
      brand: XFE
    scriptarguments:
      cveId:
        simple: ${CVE.ID}
    view: |-
      {
        "position": {
          "x": 480,
          "y": 2995
        }
      }
  "16":
    id: "16"
    taskid: ad3059da-b475-4519-824f-813ef680e24d
    type: condition
    task:
      id: ad3059da-b475-4519-824f-813ef680e24d
      version: -1
      name: VerifyContext
      description: |-
        Verifies path in context:
        - Verifies path existence
        - If matching object is an array: verify fields exists in each of the objects in the array
        - If matching object is not an array: verify fields exists in matching object
        - if 'expectedValue' is given: ensure that the given value is equal to the context path
      scriptName: Exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "14"
    scriptarguments:
      array:
        simple: ${ArraySize}
      contextKey: {}
      expectedValue:
        simple: "3"
      fields: {}
      path:
        simple: CVE
      value:
        simple: ${CVE}
    view: |-
      {
        "position": {
          "x": 480,
          "y": 2820
        }
      }
  "17":
    id: "17"
    taskid: 3b160b55-51eb-4d33-8deb-e0dd900573e8
    type: regular
    task:
      id: 3b160b55-51eb-4d33-8deb-e0dd900573e8
      version: -1
      name: VerifyContext
      description: |-
        Verifies path in context:
        - Verifies path existence
        - If matching object is an array: verify fields exists in each of the objects in the array
        - If matching object is not an array: verify fields exists in matching object
        - if 'expectedValue' is given: ensure that the given value is equal to the context path
      scriptName: VerifyContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      expectedValue:
        simple: XFE
      fields: {}
      path:
        simple: URL.Malicious.Vendor
    view: |-
      {
        "position": {
          "x": 480,
          "y": 720
        }
      }
  "18":
    id: "18"
    taskid: 8692b28a-d1e0-4d20-8c87-12d1fd6571fe
    type: regular
    task:
      id: 8692b28a-d1e0-4d20-8c87-12d1fd6571fe
      version: -1
      name: DeleteContext
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "19"
    scriptarguments:
      all:
        simple: "yes"
      key: {}
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1420
        }
      }
  "19":
    id: "19"
    taskid: 7d06af49-67a0-4bd0-821a-36dce58b605e
    type: regular
    task:
      id: 7d06af49-67a0-4bd0-821a-36dce58b605e
      version: -1
      name: file
      description: Check file reputation
      script: XFE|||file
      type: regular
      iscommand: true
      brand: XFE
    nexttasks:
      '#none#':
      - "20"
      - "21"
      - "22"
    scriptarguments:
      file:
        simple: 37c919f28798a886ec7202cc39818b8ce641ae83
      long: {}
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1595
        }
      }
  "20":
    id: "20"
    taskid: 2824f63c-893b-4969-8837-d3e687a6d22b
    type: regular
    task:
      id: 2824f63c-893b-4969-8837-d3e687a6d22b
      version: -1
      name: VerifyContext
      description: |-
        Verifies path in context:
        - Verifies path existence
        - If matching object is an array: verify fields exists in each of the objects in the array
        - If matching object is not an array: verify fields exists in matching object
        - if 'expectedValue' is given: ensure that the given value is equal to the context path
      scriptName: VerifyContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      expectedValue:
        simple: XFE
      fields: {}
      path:
        simple: File.Malicious.Vendor
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1770
        }
      }
  "21":
    id: "21"
    taskid: 4700f732-d68c-48de-851d-3f126160fbb4
    type: regular
    task:
      id: 4700f732-d68c-48de-851d-3f126160fbb4
      version: -1
      name: VerifyContext
      description: |-
        Verifies path in context:
        - Verifies path existence
        - If matching object is an array: verify fields exists in each of the objects in the array
        - If matching object is not an array: verify fields exists in matching object
        - if 'expectedValue' is given: ensure that the given value is equal to the context path
      scriptName: VerifyContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      expectedValue:
        simple: "3"
      fields: {}
      path:
        simple: DBotScore.Score
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1770
        }
      }
  "22":
    id: "22"
    taskid: 56ac17b0-a2aa-40b9-82c7-c1169c0e543d
    type: regular
    task:
      id: 56ac17b0-a2aa-40b9-82c7-c1169c0e543d
      version: -1
      name: VerifyContext
      description: |-
        Verifies path in context:
        - Verifies path existence
        - If matching object is an array: verify fields exists in each of the objects in the array
        - If matching object is not an array: verify fields exists in matching object
        - if 'expectedValue' is given: ensure that the given value is equal to the context path
      scriptName: VerifyContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      expectedValue:
        simple: 37c919f28798a886ec7202cc39818b8ce641ae83
      fields: {}
      path:
        simple: File.SHA1
    view: |-
      {
        "position": {
          "x": 910,
          "y": 1770
        }
      }
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 3040,
        "width": 1240,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
